"rrr": >-
  [Script Info]

  ; This is a Sub Station Alpha v4 script.

  Title: Neon Genesis Evangelion - Episode 26

  Original Script: RoRo

  Script Updated By: version 2.8.01

  ScriptType: v4.00

  Collisions: Normal

  PlayResY: 600

  PlayDepth: 0

  Timer: 100,0000


  [V4 Styles]

  Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour,
  BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR,
  MarginV, AlphaLevel, Encoding

  Style: DefaultVCD, Arial,28,11861244,11861244,11861244,-2147483640,-1,0,1,1,2,2,30,30,30,0,0
